### ISSUE TITLE
ERROR Application Could not import Products.AdvancedQuery

### ISSUE THREAD

**Issue by mattdmem** [senaite/senaite.lims#103]
Hello,
I'm trying to run senaite on 14.04 (AWS instance). I'v successfully installed plone 4.3.18 and built it out with senaite.lims but I get this error when trying to run! Any ideas appreciated!

Thanks

Matt

```
ubuntu:~/Plone/zinstance$ bin/instance fg
2019-04-29 14:32:23 INFO ZServer HTTP server started at Mon Apr 29 14:32:23 2019
	Hostname: 0.0.0.0
	Port: 8080
2019-04-29 14:32:24 ERROR Application Could not import Products.AdvancedQuery
Traceback (most recent call last):
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/OFS/Application.py", line 608, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/__init__.py", line 19, in <module>
    from .eval import eval as _eval, _notPassed
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/__init__.py", line 18, in <module>
    from .interfaces import IQueryContext
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/interfaces.py", line 9, in <module>
    from .transform import IOptimizer, IOrdered, IOptimizerChain, ITransformer
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/transform.py", line 102, in <module>
    from .adapter import getSubscriptionAdapter, querySubscriptionAdapter
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/adapter/__init__.py", line 44, in <module>
    from zope.interface.interfaces import ComponentLookupError
ImportError: cannot import name ComponentLookupError
Traceback (most recent call last):
  File "/home/ubuntu/Plone/zinstance/parts/instance/bin/interpreter", line 327, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/App/startup.py", line 69, in startup
    OFS.Application.import_products()
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/OFS/Application.py", line 585, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/home/ubuntu/Plone/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/OFS/Application.py", line 608, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/__init__.py", line 19, in <module>
    from .eval import eval as _eval, _notPassed
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/__init__.py", line 18, in <module>
    from .interfaces import IQueryContext
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/interfaces.py", line 9, in <module>
    from .transform import IOptimizer, IOrdered, IOptimizerChain, ITransformer
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/transform.py", line 102, in <module>
    from .adapter import getSubscriptionAdapter, querySubscriptionAdapter
  File "/home/ubuntu/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/adapter/__init__.py", line 44, in <module>
    from zope.interface.interfaces import ComponentLookupError
ImportError: cannot import name ComponentLookupError


```

**Comment by ramonski** [comment]
Hi @mattdmem,

This comes unfortunately by a broken dependency `Products.AdvancedQuery`. You need to pin it in the `[versions]` section of your buildout config to `Products.AdvancedQuery<4` and re-run `bin/buildout`.

In the latest master code we removed that dependency completely, so for 1.3.1 this shouldn't happen anymore.

**Comment by mattdmem** [comment]
Thanks - I don't think plone accepts "<" in the buildout?

`Products.AdvancedQuery < 4.0`

`An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/ubuntu/Plone/buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1994, in main
    user_defaults, command, args)
  File "/home/ubuntu/Plone/buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 231, in __init__
    data['buildout'].copy(), override, set()))
  File "/home/ubuntu/Plone/buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1608, in _open
    fp, filename_for_logging, _default_globals)
  File "/home/ubuntu/Plone/buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/configparser.py", line 234, in parse
    raise e
ParsingError: File contains parsing errors: /home/ubuntu/Plone/zinstance/buildout.cfg
	[line 180]: 'Products.AdvancedQuery < 4.0 \n'`

**Comment by ramonski** [comment]
Try it without the whitespace around the `<`

**Comment by ramonski** [comment]
Hi @mattdmem, did the suggestion above fix you issue?

**Comment by Jeff-DFWEnv** [comment]
I have the exact same situation on Ubuntu 18.04.  Unified Installer for 4.3.18 got Plone up and running fine.  Adding senaite.lims to buildout.cfg resulted in this error.

2019-05-04 20:55:44 ERROR Application Could not import Products.AdvancedQuery

Trying @ramonski suggestion now.   Will report back.

**Comment by Jeff-DFWEnv** [comment]
@mattdmem @ramonski 
Placing Products.AdvancedQuery<4 into [versions] section of buildout.cfg didn't work.  This worked:
**Products.AdvancedQuery = 3.0.4**
First problem solved.


Second problem s is permissions for plone_daemon user: 

$ sudo -u plone_daemon bin/instance fg
...
ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/Products.TextIndexNG3-3.4.14-py2.7.egg/Products/TextIndexNG3/configure.zcml", line 8.2-8.61
    IOError: [Errno 13] Permission denied: '/usr/local/Plone/buildout-cache/eggs/zopyx.txng3.core-3.6.2-py2.7.egg/zopyx/txng3/core/configure.zcml'

As with the previous version (senaite/lims 1.2.2), some files in the project folder don't have proper permission for plone_daemon.  chown was required.

**Comment by raissafedora** [comment]
@mattdmem :
use "=<4"

**Comment by ramonski** [comment]
Closing this issue, because newer versions of senaite.core do not rely anymore on `Products.AdvancedQuery`
