### ISSUE TITLE
Sticker printing in Batches fails. Object has no attribute 'getSampler'

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#38]
Auto Sticker printing works well (say at Sample _Receive_) from lists, also on the Print Stickers button, and but produces an error when done from LIMS Batches.

## Steps to reproduce

System set on auto label printing at _Recieve_, Navigate to a Batch containing _Due_ Samples/ARs, select a few and _Receive_ them

## Current behavior

All of the sticker templates, gives an _object has no attribute 'getSampler'_ error at e.g. /batches/B-003/sticker?template=Code_128_1x48mm.pt&items=AP-0055-R01,AP-0056-R01,...

B-003 - Unable to load the template 'Code_128_1x48mm.pt':
Traceback (most recent call last):
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/stickers.py", line 269, in renderItem
    return embed(self)
  File "/home/bika/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/bika/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/bika/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/bika/buildout-cache/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/bika/buildout-cache/eggs/Chameleon-3.1-py2.7.egg/chameleon/zpt/template.py", line 289, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/bika/buildout-cache/eggs/Chameleon-3.1-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/bika/buildout-cache/eggs/Chameleon-3.1-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "0b4ed0c97dbdb0bbb114fc5a0c0ed3e5.py", line 150, in render
AttributeError: 'NoneType' object has no attribute 'getSampler'

 - Expression: "python:sample.getSampler()"
 - Filename:   ... /bika/lims/browser/templates/stickers/Code_128_1x48mm.pt
 - Location:   (line 26: col 14)
 - Source:     sampler           python:sample.getSampler();
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  modules: 
               sample: 
               ar: 
               container: 
               wrapped_repeat: 
               portal_url: https://senaite.ridingbytes.com
               traverse_subpath: 
               partnr: 003
               template: 
               translate: 
               repeat: {...} (0)
               views: 
               args: 
               here: 
               part: 
               user: 
               nothing: 
               ar_id: 
               default: 
               request: 
               item: 
               loop: {...} (0)
               context: 
               portal_state: 
               view: 
               root: 
               options: {...} (0)
               target_language: 

## Expected behavior

The stickers to be rendered for printing according the selected template, as it does now on AR lists outside Batches

![image](https://user-images.githubusercontent.com/1196034/34353955-b4e87234-ea33-11e7-8575-93bae8cac67a.png)

**Comment by lemoene** [comment]
Wait... seems Sampler does not get captured at times

**Comment by lemoene** [comment]
Jip, batches allow Sampling without a Sampler selected. Outside Batches, LIMS does nothing - a message 'Sampler required' should do in both instances. On another thread
